export const $ = document.querySelector.bind(document);
export const $$ = document.querySelectorAll.bind(document);

export const el = {
    navItems: $$('.nav-item'),
    pages: $$('.page'),
    statusDot: $('#backend-status .status-dot'),
    statusText: $('#backend-status .status-text'),
    gpuBadge: $('#gpu-badge'),
    gpuDetail: $('#gpu-detail'),
    gpuChip: $('#gpu-chip'),
    cudaVersion: $('#cuda-version'),
    canvasOrig: $('#canvas-original'),
    canvasResult: $('#canvas-result'),
    dropZone: $('#drop-zone'),
    subtitleOverlay: $('#subtitle-overlay'),
    resultPlaceholder: $('#result-placeholder'),
    btnOpenFile: $('#btn-open-file'),
    btnOutputDir: $('#btn-output-dir'),
    btnDrawRegion: $('#btn-draw-region'),
    regionsPanel: $('#regions-panel'),
    regionsList: $('#regions-list'),
    maskMode: $('#mask-mode'),
    timelineOrig: $('#timeline-orig'),
    frameInfoOrig: $('#frame-info-orig'),
    btnPlayOrig: $('#btn-play-orig'),
    pipelineSteps: $$('.pipeline-step'),
    pipelinePanes: $$('.pipeline-pane'),
    btnUploadStep1: $('#btn-upload-step1'),
    btnPrevOrig: $('#btn-prev-orig'),
    btnNextOrig: $('#btn-next-orig'),
    timelineResult: $('#timeline-result'),
    frameInfoResult: $('#frame-info-result'),
    btnPlayResult: $('#btn-play-result'),
    btnPrevResult: $('#btn-prev-result'),
    btnNextResult: $('#btn-next-result'),
    metaName: $('#meta-name'),
    metaRes: $('#meta-res'),
    metaFps: $('#meta-fps'),
    metaDur: $('#meta-dur'),
    modeAuto: $('#mode-auto'),
    modeManual: $('#mode-manual'),
    algoSelect: $('#algo-select'),

    btnStart: $('#btn-start'),
    btnCancel: $('#btn-cancel'),
    progressSection: $('#progress-section'),
    progressBar: $('#progress-bar'),
    progressLabel: $('#progress-label'),
    progressEta: $('#progress-eta'),
    logOutput: $('#log-output'),
    btnCopyLog: $('#btn-copy-log'),
    btnClearLog: $('#btn-clear-log'),
    jobList: $('#job-list'),
    aiProvider: $('#ai-provider'),
    cloudAiPanel: $('#cloud-ai-panel'),
    localAiPanel: $('#local-ai-panel'),
    apiKeyList: $('#api-key-list'),
    btnAddAiKey: $('#btn-add-ai-key'),
    btnTestAiKeys: $('#btn-test-ai-keys'),
    aiModel: $('#ai-model'),
    aiEndpoint: $('#ai-endpoint'),
    btnScanOllama: $('#btn-scan-ollama'),
    ollamaModelSelect: $('#ollama-model-select'),
    btnAddOllamaModel: $('#btn-add-ollama-model'),
    ollamaModelList: $('#ollama-model-list'),
    aiPrompt: $('#ai-prompt'),
    ttsVoice: $('#tts-voice'),
    ttsLanguage: $('#tts-language'),
    ttsBgVolume: $('#tts-bg-volume'),
    ttsRemoveVocal: $('#tts-remove-vocal'),
    volLabel: $('#vol-label'),
    btnSaveAi: $('#btn-save-ai'),
    ttsStatusChip: $('#tts-status-chip'),
    cloneVoiceName: $('#clone-voice-name'),
    btnUploadRefAudio: $('#btn-upload-ref-audio'),
    refAudioName: $('#ref-audio-name'),
    refAudioPreview: $('#ref-audio-preview'),
    btnCloneVoice: $('#btn-clone-voice'),
    savedVoicesList: $('#saved-voices-list'),
    ttsTestText: $('#tts-test-text'),
    btnTestTts: $('#btn-test-tts'),
    ttsTestAudio: $('#tts-test-audio'),
    // Content panels
    chkTtsGenerate: $('#chk-tts-generate'),
    panelSrt: $('#panel-srt'),
    panelAi: $('#panel-ai'),
    panelVoice: $('#panel-voice'),
    srtContent: $('#srt-content'),
    aiContent: $('#ai-content'),
    voiceSegments: $('#voice-segments'),
    // Panel action buttons
    btnAiRegenerate: $('#btn-ai-regenerate'),
    btnAiImport: $('#btn-ai-import'),
    btnAiApply: $('#btn-ai-apply'),
    btnVoiceRegenerate: $('#btn-voice-regenerate'),
    btnVoiceImport: $('#btn-voice-import'),
    btnVoiceApply: $('#btn-voice-apply'),
    // Voice sub panel
    chkVoiceSub: $('#chk-voice-sub'),
    panelVoiceSub: $('#panel-voice-sub'),
    voicesubContent: $('#voicesub-content'),
    voicesubMode: $('#voicesub-mode'),
    btnVoicesubImport: $('#btn-voicesub-import'),
    btnVoicesubApply: $('#btn-voicesub-apply'),
    // Resize handles
    resizeHandle1: $('#resize-handle-1'),
    resizeHandle2: $('#resize-handle-2'),
  };
